### ISSUE TITLE
 label_array not defined: Chapter 4 Page 92

### ISSUE THREAD

**Issue by johnosbb** [PacktPublishing/Artificial-Intelligence-for-IoT-Cookbook#1]
On page 92 Chapter 4
There is the following sequence of code.

```
nb_features = seq_array.shape[2]
nb_out = label_array.shape[1]
model = Sequential()
model.add(LSTM(input_shape=(sequence_length, nb_features),
 units=100, return_sequences=True))
model.add(Dropout(0.25))
```

But  label_array is not defined in any of the previous code.

What shape should  label_array be?

**Comment by rajat-packt** [comment]
Hey @Microshak would you be able to help out with this?

**Comment by rajat-packt** [comment]
Hey @johnosbb,

I am currently unable to get in touch with the author for this query, but please try these potential workarounds in the meantime:

In the code snippet provided, `label_array` is mentioned, but it's not explicitly defined within the provided context. However, based on its usage in `label_array.shape[1]`, we can infer that `label_array` is likely an array or tensor containing labels or target values for the LSTM model.

To determine the shape of `label_array`, we need to consider its usage in the context of the model's architecture, particularly in relation to the output layer. 

Here's a breakdown:

- `label_array.shape[1]` is used to extract the size of the second dimension of `label_array`.
- The output shape of the LSTM layer (`return_sequences=True`) will be `(sequence_length, units)` for each timestep.
- Since `return_sequences=True`, the output of the LSTM layer will be a sequence of vectors for each timestep.
- The subsequent layer after LSTM is not shown, but it's reasonable to assume that it will have an output shape compatible with the labels.

Without further context, we can't provide an exact shape for `label_array`, but typically, it should have a shape compatible with the output shape of the LSTM layer. If the model is used for a classification task with `nb_out` classes, a common shape for `label_array` would be `(num_samples, nb_out)`, where `num_samples` is the number of samples in the dataset and `nb_out` is the number of output classes.

I am closing this issue for now, please feel free to reopen it or create a new issue if you still need help.
